---
- name: Add jenkins repository
  ansible.builtin.yum_repository:
    name: jenkins
    description: Jenkins Repository
    baseurl: https://pkg.jenkins.io/redhat-stable
    gpgcheck: true
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
