---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian11
    image: debian:11
  - name: debian12
    image: debian:12
  - name: fedora39
    image: fedora:39
    dockerfile: fedora-39
    privileged: true
    cgroupns_mode: host
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: /usr/sbin/init
  - name: fedora40
    image: fedora:40
    dockerfile: fedora-40
    privileged: true
    cgroupns_mode: host
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: /usr/sbin/init
  - name: ubuntu2004
    image: ubuntu:20.04
  - name: ubuntu2204
    image: ubuntu:22.04
  - name: ubuntu2304
    image: ubuntu:23.04
  - name: ubuntu2310
    image: ubuntu:23.10
  - name: ubuntu2404
    image: ubuntu:24.04
provisioner:
  name: ansible
verifier:
  name: ansible
